### ISSUE TITLE
Find and Replace a high amount of fonts without the ability to scroll down 

### ISSUE THREAD

**Issue by NeonGreenn** [partyka1/Fontily#1]
Hi,
in case you got numerous fonts to display:

![fontily-issue_no-scroll](https://cloud.githubusercontent.com/assets/9961557/21387950/681503f0-c77a-11e6-902a-62b5ae7a521f.png)

The possibility to scroll down or even resize the modal would be useful.

Greetings

**Comment by kietnguyen** [comment]
I have this issue too. Please add this feature. Thanks.

**Comment by p6m459** [comment]
Hi, I'm aware of the issue and I'm working on implementing scroll view. Should be ready soon :)
