### ISSUE TITLE
Add support for Dark Theme

### ISSUE THREAD

**Issue by ryangwilson** [partyka1/Fontily#5]
When using Fontily on Sketch 53.2 the Find and Replace modal looks like this:
![Screen Shot 2019-04-12 at 7 19 18 AM](https://user-images.githubusercontent.com/4571457/56033859-7e764800-5cf3-11e9-8145-7f5a637eb99b.png)

If you squint you can read the font names ;)

**Comment by partyka1** [comment]
it should be fixed by nox thanks to #7

**Comment by p6m459** [comment]
it should be fixed by nox thanks to @simonkuran and #7
